### PR TITLE
Feature tablayout

### PR DESCRIPTION
**Pull request by bot2x**
This PR includes the following:

- It creates a tab layout.
- A tab controller for centrally managing the operations related to the tab layout.
- Refs for the current selected tab which can be used by other modules for tab context,
- Skeletal for the Tab primitive which will provide operations pertaining to a particular tab.

### CODE REVIEW

**Comment by bot2x** [comment]
@code-master-ajay @niharT9 Please go through this and give a go ahead before we merge this. We can discuss the design choices and see if any changes are required for the facilitation in the further feature additions.

**Comment by code-master-ajay** [comment]
Hi @bot2x , i tested the functionality, It seems that if i delete the placeholder text and then type something. all the previous tabs display the same data, and then if i open a new tab the same data is appended in front of the placeholder text of the new tab.Can you please check it out. 

Steps to reproduce:
1. Go to tab 2 
2. Delete placeholder text
3. Keep pressing backspace until the cursor size becomes small (Not sure why this happens)
4. Whatever you type will be now displayed in tab 1 aslo.

Do let me know if you have any questions.

**Comment by code-master-ajay** [comment]
I also noticed this minor css issue, the spacing is not even between the tab buttons.

image

**Comment by bot2x** [comment]
> I also noticed this minor css issue, the spacing is not even between the tab buttons.
> 
> image

Yes. I had ignored it intentionally. Have corrected it in latest commits. Will flow the changes in this soon.

**Comment by bot2x** [comment]
> Hi @bot2x , i tested the functionality, It seems that if i delete the placeholder text and then type something. all the previous tabs display the same data, and then if i open a new tab the same data is appended in front of the placeholder text of the new tab.Can you please check it out.
> 
> Steps to reproduce:
> 
> 1. Go to tab 2
> 2. Delete placeholder text
> 3. Keep pressing backspace until the cursor size becomes small (Not sure why this happens)
> 4. Whatever you type will be now displayed in tab 1 aslo.
> 
> Do let me know if you have any questions.

Interesting. I didn't check it. In the latest development - I have some major structural changes which should ideally take care of these cross ref issues. I'll merge those changes in this PR shortly. Then we can merge all those changes together.

**Comment by bot2x** [comment]
@code-master-ajay How does this look now ?

**Pull request merged**
